### ISSUE TITLE
provide better documentation

### ISSUE THREAD

**Issue by montrealist** [getshifter/go-create-shifter-package#1]
The [user guide](https://support.getshifter.io/user-guide/how-to-import-your-wordpress-site-into-shifter) step mentions to "Download Create Shifter Package", though I find it's too concise and missing important information. In the README to this repository it would be great to at least mention what `gox` is and where we can get it from. Thanks!

**Comment by sawanoboly** [comment]
To use this you can download the prebuilt binaries. I updated the README so that it makes it easy to understand.
